-- STICKBLADE ARENA — Supabase schema
-- Run this once in: Supabase Dashboard -> SQL Editor -> New query -> Run
-- Then create a Storage bucket named: replays   (private is fine)

create table if not exists matches (
    id          text primary key,
    created     double precision,
    model_a     text,
    model_b     text,
    sharp       text,
    weapon      text default 'sword',     -- sword | flail | bow
    status      text,                     -- queued | running | done | error
    winner_side text,                     -- a | b | draw (CANVAS side: a=green, b=blue)
    method      text,
    turns       integer,
    error       text,
    blind       boolean default true,
    voted       boolean default false,
    -- True = the user's model_a was rendered as the BLUE (Fighter B) ragdoll.
    -- Server picks this at queue time so the picker can't leak identity.
    flip        boolean default false,
    -- 2-sentence post-fight commentary/roast generated by a 3rd LLM
    commentary  text
);

create table if not exists votes (
    id        text primary key,
    match_id  text references matches(id),
    created   double precision,
    choice    text                          -- a | b | draw (CANVAS side)
);

-- Per-weapon, per-sharp Elo leaderboards. (model, sharp, weapon) is the PK.
create table if not exists elo (
    model   text,
    sharp   text,
    weapon  text default 'sword',
    rating  double precision default 1000,
    wins    integer default 0,
    losses  integer default 0,
    draws   integer default 0,
    primary key (model, sharp, weapon)
);

create index if not exists idx_matches_created on matches (created desc);
create index if not exists idx_elo_sharp on elo (sharp, rating desc);
create index if not exists idx_elo_weapon on elo (weapon, rating desc);

-- The backend uses the service_role key (bypasses RLS), so RLS can stay
-- enabled with no public policies = tables are NOT readable by anonymous users.
alter table matches enable row level security;
alter table votes   enable row level security;
alter table elo     enable row level security;

-- ============================================================
-- IDEMPOTENT MIGRATION (safe to run on an existing deployment)
-- ============================================================
alter table matches add column if not exists weapon     text default 'sword';
alter table matches add column if not exists flip       boolean default false;
alter table matches add column if not exists commentary text;
alter table elo     add column if not exists weapon     text default 'sword';
-- Promote the elo PK to include weapon (only if it doesn't already):
do $$
begin
  if not exists (
    select 1 from information_schema.table_constraints
    where  table_name = 'elo' and constraint_type = 'PRIMARY KEY'
    and    constraint_name like '%weapon%'
  ) then
    alter table elo drop constraint if exists elo_pkey;
    alter table elo add primary key (model, sharp, weapon);
  end if;
end$$;
