-- STICKBLADE ARENA — Supabase schema
-- Run this in: Supabase Dashboard -> SQL Editor -> New query -> Run
-- Safe to run on a FRESH project AND on an existing populated database.
-- Then create a Storage bucket named: replays (private is fine).

-- ============================================================================
-- 1. CREATE TABLES (no-op on existing tables, full schema on fresh installs)
-- ============================================================================
create table if not exists matches (
    id          text primary key,
    created     double precision,
    model_a     text,
    model_b     text,
    sharp       text,
    weapon      text default 'sword',     -- sword | dagger | spear | flail | bow
    status      text,                     -- queued | running | done | error
    winner_side text,                     -- a | b | draw (CANVAS side: a=green, b=blue)
    method      text,
    turns       integer,
    error       text,
    blind       boolean default true,
    voted       boolean default false,
    -- True = the user's model_a was rendered as the BLUE (Fighter B) ragdoll.
    -- Server picks this at queue time so the picker can't leak identity.
    flip        boolean default false,
    -- 2-sentence post-fight commentary/roast generated by a 3rd LLM
    commentary  text
);

create table if not exists votes (
    id        text primary key,
    match_id  text references matches(id),
    created   double precision,
    choice    text                          -- a | b | draw (CANVAS side)
);

-- Per-weapon, per-sharp Elo leaderboards. (model, sharp, weapon) is the PK.
create table if not exists elo (
    model   text,
    sharp   text,
    weapon  text default 'sword',
    rating  double precision default 1000,
    wins    integer default 0,
    losses  integer default 0,
    draws   integer default 0,
    primary key (model, sharp, weapon)
);

create table if not exists tournaments (
    id            text primary key,
    created       double precision,
    name          text,
    size          integer,
    weapon        text default 'sword',
    sharp         text,
    arena         text default 'normal',
    mode          text default 'macro',
    status        text,                 -- queued | running | done | error
    current_round integer default 0,
    winner_model  text,
    models        text,                 -- JSON array of model ids in seed order
    error         text
);

create table if not exists tournament_matches (
    id            serial primary key,
    tournament_id text references tournaments(id),
    round         integer,
    slot          integer,
    match_id      text,
    model_a       text,
    model_b       text,
    winner_model  text,
    unique (tournament_id, round, slot)
);

-- ============================================================================
-- 2. IDEMPOTENT MIGRATIONS for older deployments
--    Must run BEFORE any CREATE INDEX or PK change that references new columns.
-- ============================================================================
alter table matches add column if not exists weapon     text default 'sword';
alter table matches add column if not exists flip       boolean default false;
alter table matches add column if not exists commentary text;
alter table elo     add column if not exists weapon     text default 'sword';

-- Backfill any rows that pre-date the weapon column so the new PK won't
-- complain about NULLs. (default 'sword' only applies to NEW rows.)
update elo     set weapon = 'sword' where weapon is null;
update matches set weapon = 'sword' where weapon is null;

-- Promote the elo PK to include `weapon` — only if it hasn't been promoted yet.
do $$
declare
  has_weapon_pk boolean;
begin
  select exists (
    select 1
    from   pg_index i
    join   pg_attribute a
           on a.attrelid = i.indrelid and a.attnum = any(i.indkey)
    where  i.indrelid = 'public.elo'::regclass
    and    i.indisprimary
    and    a.attname  = 'weapon'
  ) into has_weapon_pk;

  if not has_weapon_pk then
    -- drop whatever the old PK was (likely (model, sharp))
    alter table elo drop constraint if exists elo_pkey;
    alter table elo add primary key (model, sharp, weapon);
  end if;
end$$;

-- ============================================================================
-- 3. INDEXES (safe now that all columns exist)
-- ============================================================================
create index if not exists idx_matches_created          on matches            (created desc);
create index if not exists idx_elo_sharp                on elo                (sharp,  rating desc);
create index if not exists idx_elo_weapon               on elo                (weapon, rating desc);
create index if not exists idx_tournament_matches_tid   on tournament_matches (tournament_id, round, slot);

-- ============================================================================
-- 3b. ATOMIC ELO UPDATE — server-side function.
--     The Python record_vote() path used to do
--         GET elo -> compute in Python -> PATCH elo
--     with no lock, which lost updates when two votes for the same
--     (model, sharp, weapon) landed within the same READ window.
--     This RPC does the whole read-modify-write inside a single
--     transaction with row-level UPSERTs, so concurrent votes serialize
--     via Postgres' MVCC + PK constraint instead of silently clobbering.
--
--     Signature:
--       apply_elo_vote(a_model, b_model, sharp, weapon, choice_model)
--     choice_model is 'a', 'b', or 'draw' (already unflipped for canvas
--     side by the caller). Returns d_a and d_b so the caller can echo
--     them back in the reveal payload.
-- ============================================================================
create or replace function apply_elo_vote(
    a_model      text,
    b_model      text,
    p_sharp      text,
    p_weapon     text,
    choice_model text,   -- 'a' | 'b' | 'draw'
    k_factor     numeric default 32,
    start_elo    numeric default 1000
) returns table (d_a numeric, d_b numeric)
language plpgsql
as $$
declare
    ra_rating numeric;
    rb_rating numeric;
    ea numeric;
    sa numeric;
    dda numeric;
    ddb numeric;
begin
    -- Ensure both rows exist. ON CONFLICT DO NOTHING is atomic and
    -- respects the (model, sharp, weapon) PK.
    insert into elo(model, sharp, weapon, rating, wins, losses, draws)
      values (a_model, p_sharp, p_weapon, start_elo, 0, 0, 0)
      on conflict (model, sharp, weapon) do nothing;
    insert into elo(model, sharp, weapon, rating, wins, losses, draws)
      values (b_model, p_sharp, p_weapon, start_elo, 0, 0, 0)
      on conflict (model, sharp, weapon) do nothing;

    -- Lock both rows for the duration of this txn. Row order (model asc)
    -- prevents deadlocks when two votes concurrently touch the same pair
    -- with reversed a/b.
    perform 1
      from elo
      where (model, sharp, weapon) in
            ((a_model, p_sharp, p_weapon), (b_model, p_sharp, p_weapon))
      order by model
      for update;

    select rating into ra_rating
      from elo where model = a_model and sharp = p_sharp and weapon = p_weapon;
    select rating into rb_rating
      from elo where model = b_model and sharp = p_sharp and weapon = p_weapon;

    ea := 1.0 / (1.0 + 10 ^ ((rb_rating - ra_rating) / 400.0));
    sa := case choice_model
              when 'a'    then 1.0
              when 'b'    then 0.0
              else             0.5
          end;
    dda := k_factor * (sa - ea);
    ddb := k_factor * ((1.0 - sa) - (1.0 - ea));

    -- Self-play (mirror match): both fighters ARE the same row. Elo
    -- delta must be zero (you can't gain rating from beating yourself),
    -- and W/L should cancel to a single draw entry so the total match
    -- count is at least visible in the leaderboard. Without this
    -- special case both UPDATEs would hit the same row twice and either
    -- double-count or clobber depending on ordering.
    if a_model = b_model then
        update elo
           set draws = draws + 1
         where model = a_model and sharp = p_sharp and weapon = p_weapon;
        return query select 0::numeric, 0::numeric;
        return;
    end if;

    update elo
       set rating = rating + dda,
           wins   = wins   + case when choice_model = 'a'    then 1 else 0 end,
           losses = losses + case when choice_model = 'b'    then 1 else 0 end,
           draws  = draws  + case when choice_model = 'draw' then 1 else 0 end
     where model = a_model and sharp = p_sharp and weapon = p_weapon;

    update elo
       set rating = rating + ddb,
           wins   = wins   + case when choice_model = 'b'    then 1 else 0 end,
           losses = losses + case when choice_model = 'a'    then 1 else 0 end,
           draws  = draws  + case when choice_model = 'draw' then 1 else 0 end
     where model = b_model and sharp = p_sharp and weapon = p_weapon;

    return query select dda, ddb;
end$$;

-- ============================================================================
-- 4. ROW LEVEL SECURITY
--    Backend uses the service_role key (bypasses RLS), so RLS enabled with
--    no public policies = tables are NOT readable by anonymous users.
-- ============================================================================
alter table matches            enable row level security;
alter table votes              enable row level security;
alter table elo                enable row level security;
alter table tournaments        enable row level security;
alter table tournament_matches enable row level security;
