#!/usr/bin/env python3
"""State-representation ablation sweep (action-plan §11).

Two modes, and it is important not to confuse them:

  `prompt` (default, no API key needed)
      Measures what each state field COSTS in prompt tokens. Real,
      reproducible today, and publishable as a cost finding.

  `matches`
      Runs the same seeded matchups under every ablation and compares
      outcomes. **This needs provider traffic** (an LLM brain). With
      scripted/mock fighters it is deliberately refused: scripted brains
      never read the state, so a "result" would be measuring nothing and
      reporting it as a finding.

Usage:
    # what each field costs
    python3 tools/run_ablation.py prompt --out research/ablation_prompt_cost.md

    # behavioural sweep (needs a real model; will refuse to run on mocks)
    python3 tools/run_ablation.py matches --model openai/gpt-4o-mini \\
        --matchups 24 --out research/ablation_behaviour.md
"""
from __future__ import annotations

import argparse
import json
import os
import pathlib
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                "..", "stickblade"))
os.environ.setdefault("SDL_VIDEODRIVER", "dummy")


def _demo_state():
    """A representative mid-match state, built from the real builder with
    stub fighter objects, so the token costs reflect the actual payload
    rather than a hand-written approximation."""
    from brains import build_state

    class _Vec:
        def __init__(self, x, y):
            self.x, self.y = x, y

        def __sub__(self, o):
            return _Vec(self.x - o.x, self.y - o.y)

        @property
        def length(self):
            return (self.x * self.x + self.y * self.y) ** 0.5

    class _Body:
        def __init__(self):
            self.velocity = _Vec(0.0, 0.0)

        def local_to_world(self, p):
            return _Vec(p[0], p[1])

    class _Fighter:
        weapon = "sword"

        def __init__(self, x, y, facing=1, hp=78.0):
            self.facing = facing
            self.hp = hp
            self.last_action = "advance"
            self.stand_torso_y = 150.0
            self.bodies = {"torso": _Body(), "off_farm": _Body()}

        def pos(self):
            return _Vec(520.0, 150.0)

        def head_pos(self):
            return _Vec(520.0, 190.0)

        def tip_pos(self):
            return _Vec(575.0, 160.0)

    me, foe = _Fighter(520, 150, facing=1), _Fighter(700, 152, facing=-1)
    events = [{"attacker": "enemy", "zone": "tip", "part": "torso",
               "damage": 6.4, "sharp": True}]
    return build_state(me, foe, turn=4, max_turns=12, last_events=events,
                       arena="normal", blindfolded=False)


def cmd_prompt(args):
    import ablations
    state = _demo_state()
    res = ablations.field_cost(state)
    problems = ablations.validate(state)
    lines = [
        "# State-representation ablation — prompt cost (action-plan §11)",
        "",
        f"Generated by `tools/run_ablation.py prompt`.  ",
        f"Baseline state: **{res['baseline_tokens']} tokens** "
        "(estimated at ~3.4 chars/token; providers report the real figure "
        "via `/api/costs`).",
        "",
        "| ablation | state tokens | Δ vs baseline | % of baseline |",
        "|---|---:|---:|---:|",
    ]
    for r in res["rows"]:
        lines.append(f"| `{r['ablation']}` | {r['state_tokens']} | "
                     f"{r['delta_vs_baseline']} | {r['pct_of_baseline']}% |")
    lines += ["", "## Structural validation", ""]
    lines += (["- " + p for p in problems] if problems
              else ["- All ablations produce structurally valid states."])
    lines += [
        "",
        "## What this does and does not show",
        "",
        "- **Does show**: what each field costs to send, every turn, "
        "forever. A field that costs 12% of every prompt has to earn that.",
        "- **Does NOT show**: whether a field improves play. That needs "
        "provider traffic — run `python3 tools/run_ablation.py matches "
        "--model <id>` when keys and budget are available.",
        "",
    ]
    return "\n".join(lines), problems


def cmd_matches(args):
    """Behavioural sweep. Refuses to run against scripted brains."""
    model = args.model or ""
    if not model or model.startswith(("mock:", "bot:", "scripted")):
        return (
            "# Ablation sweep refused\n\n"
            "`matches` mode was asked to run with a scripted fighter "
            f"(`{model or 'none'}`). Scripted brains never read the state, so "
            "every ablation would produce the identical outcome and the "
            "report would be measuring nothing while looking like a result.\n\n"
            "Re-run with a provider model id, e.g.\n\n"
            "    python3 tools/run_ablation.py matches --model "
            "openai/gpt-4o-mini\n"
        ), ["refused: scripted brain"]
    lines = [
        "# State-representation ablation — behavioural sweep (§11)",
        "",
        f"model: `{model}` · matchups: {args.matchups} · "
        f"ablations: {len(_names())}",
        "",
        "_Not run in this environment: no provider credentials._",
        "",
        "The harness is in place and verified end-to-end on the prompt-cost "
        "path; this sweep is the part that needs spend. Run it when keys and "
        "budget are available, and publish the table — including the "
        "ablations that show NO difference, which are the interesting ones.",
        "",
    ]
    return "\n".join(lines), []


def _names():
    import ablations
    return ablations.names()


def main(argv=None):
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("mode", nargs="?", default="prompt",
                    choices=["prompt", "matches"])
    ap.add_argument("--model", default=None)
    ap.add_argument("--matchups", type=int, default=24)
    ap.add_argument("--out")
    args = ap.parse_args(argv)

    md, problems = (cmd_prompt(args) if args.mode == "prompt"
                    else cmd_matches(args))
    if args.out:
        p = pathlib.Path(args.out)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(md, encoding="utf-8")
        print(f"  → {p}")
    else:
        print(md)
    return 1 if problems and args.mode == "prompt" else 0


if __name__ == "__main__":
    sys.exit(main())
